# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
          context: user
          pattern: /.*
          form_login:
                provider: fos_userbundle
          oauth:
            resource_owners:
              facebook: "/socialLogin/check-facebook"   
            login_path: /login
            failure_path: /login
            oauth_user_provider:
              service: ens.oauth.user_provider
          logout: true
          anonymous: true
        # main:
        #     pattern: ^/
        #     form_login:
        #         provider: fos_userbundle
        #     logout:       true
        #     anonymous:    true
        #     oauth:
        #         resource_owners:
        #             facebook: "/login/check-facebook"
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
