Ens\CvBundle\Entity\CategoryCvAffiliate:
  type: entity
  table: category_affiliateCv
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  manyToOne:
    categoryCv:
      targetEntity: CategoryCv
      inversedBy: category_affiliatesCv
      joinColumn:
        name: category_id
        referencedColumnName: id
    AffiliateCv:
      targetEntity: AffiliateCv
      inversedBy: category_affiliatesCv
      joinColumn:
        name: affiliate_id
        referencedColumnName: id