ens_job:
    path:     /
    defaults: { _controller: "EnsGoodJobBundle:Job:index" }

ens_job_show:
    pattern: /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsGoodJobBundle:Job:show" }
    requirements:
        id: \d+

ens_job_preview:
    pattern: /{company}/{location}/{token}/{position}
    defaults: { _controller: "EnsGoodJobBundle:Job:preview" }
    requirements:
        token: \w+

ens_job_new:
    path:     /new
    defaults: { _controller: "EnsGoodJobBundle:Job:new" }

ens_job_create:
    path:     /create
    defaults: { _controller: "EnsGoodJobBundle:Job:create" }
    requirements: { _method: post }

ens_job_edit:
    path:     /{token}/edit
    defaults: { _controller: "EnsGoodJobBundle:Job:edit" }

ens_job_update:
    path:     /{token}/update
    defaults: { _controller: "EnsGoodJobBundle:Job:update" }
    requirements: { _method: post }

ens_job_delete:
    path:     /{token}/delete
    defaults: { _controller: "EnsGoodJobBundle:Job:delete" }
    requirements: { _method: post }

ens_job_publish:
    pattern: /{token}/publish
    defaults: { _controller: "EnsGoodJobBundle:Job:publish" }
    requirements: { _method: post }
ens_job_extend:
    pattern:  /{token}/extend
    defaults: { _controller: "EnsGoodJobBundle:Job:extend" }
    requirements: { _method: post }